/**
 * Fil rouge SNT
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApiAnneeScolairesGetCollection200ResponseHydraSearchHydraMappingInner } from './apiAnneeScolairesGetCollection200ResponseHydraSearchHydraMappingInner';


export interface ApiAnneeScolairesGetCollection200ResponseHydraSearch { 
    type?: string;
    hydratemplate?: string;
    hydravariableRepresentation?: string;
    hydramapping?: Array<ApiAnneeScolairesGetCollection200ResponseHydraSearchHydraMappingInner>;
}

