/**
 * Fil rouge SNT
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { InscriptionJsonldRead } from './inscriptionJsonldRead';
import { ApiAnneeScolairesGetCollection200ResponseHydraSearch } from './apiAnneeScolairesGetCollection200ResponseHydraSearch';
import { ApiAnneeScolairesGetCollection200ResponseHydraView } from './apiAnneeScolairesGetCollection200ResponseHydraView';


export interface ApiInscriptionsGetCollection200Response { 
    hydramember: Array<InscriptionJsonldRead>;
    hydratotalItems?: number;
    hydraview?: ApiAnneeScolairesGetCollection200ResponseHydraView;
    hydrasearch?: ApiAnneeScolairesGetCollection200ResponseHydraSearch;
}

