/**
 * Fil rouge SNT
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 */
export interface ClasseJsonld { 
    readonly id?: number;
    libelle: string;
    inscriptions?: Array<string>;
    niveau?: string | null;
    filiere?: string | null;
    ouvertures?: Array<string>;
    cours?: Array<string>;
    nbEtudiants?: number | null;
}

