/**
 * Fil rouge SNT
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OuvertureJsonldRead } from './ouvertureJsonldRead';
import { NiveauJsonldRead } from './niveauJsonldRead';
import { CoursJsonldRead } from './coursJsonldRead';
import { FiliereJsonldRead } from './filiereJsonldRead';


/**
 * 
 */
export interface ClasseJsonldRead { 
    context?: string | null;
    readonly id?: string;
    readonly type?: string;
    libelle: string;
    niveau?: NiveauJsonldRead | null;
    filiere?: FiliereJsonldRead | null;
    ouvertures?: Array<OuvertureJsonldRead>;
    cours?: Array<CoursJsonldRead>;
    nbEtudiants?: number | null;
}

