/**
 * Fil rouge SNT
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 */
export interface Cours { 
    readonly id?: number;
    heures?: number;
    semestre?: number;
    module?: string;
    readonly annee_scolaire?: string;
    classe?: string;
    sessionCours?: Array<string>;
    anneeScolaire?: string | null;
}

