/**
 * Fil rouge SNT
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ClasseJsonldWrite } from './classeJsonldWrite';
import { AnneeScolaireJsonldWrite } from './anneeScolaireJsonldWrite';


/**
 * 
 */
export interface OuvertureJsonldWrite { 
    context?: string | null;
    readonly id?: string;
    readonly type?: string;
    classe?: ClasseJsonldWrite;
    readonly annee_scolaire?: AnneeScolaireJsonldWrite;
}

