/**
 * Fil rouge SNT
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SalleJsonldRead } from './salleJsonldRead';
import { ProfesseurJsonldRead } from './professeurJsonldRead';
import { CoursJsonldRead } from './coursJsonldRead';


/**
 * 
 */
export interface SessionCoursJsonldRead { 
    context?: string | null;
    readonly id?: string;
    readonly type?: string;
    cours?: CoursJsonldRead | null;
    heureDebut?: string;
    heureFin?: string;
    date?: string;
    duree?: string | null;
    salle?: SalleJsonldRead;
    professeur?: ProfesseurJsonldRead | null;
}

