/**
 * Fil rouge SNT
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CoursRead } from './coursRead';
import { SalleRead } from './salleRead';
import { ProfesseurRead } from './professeurRead';


/**
 * 
 */
export interface SessionCoursRead { 
    cours?: CoursRead | null;
    heureDebut?: string;
    heureFin?: string;
    date?: string;
    duree?: string | null;
    salle?: SalleRead | null;
    professeur?: ProfesseurRead | null;
    presentiel?: boolean;
    valide?: boolean;
}

