/**
 * Fil rouge SNT
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 */
export interface User { 
    readonly id?: number;
    email?: string;
    roles?: Array<string>;
    /**
     * The hashed password
     */
    password?: string;
    readonly username?: string;
    /**
     * A visual identifier that represents this user.
     */
    readonly userIdentifier?: string;
}

